language: python

python:
  - 3.5

services: postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=Arquitran.settings.travis

install:
  - pip install -r requirements.txt

script:
  - python manage.py test
