version: '2'
services:
  proxy:
    image: abiosoft/caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    links:
      - django
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./.caddy:/root/.caddy

  postgresql:
    image: postgres
    volumes:
      - alquitrandata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=alquitran_db
      - POSTGRES_USER=alquitran_eduardo
      - POSTGRES_PASSWORD

  django:
    build: .
    restart: always
    depends_on:
      - postgresql
    environment:
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=Arquitran.settings.production
      - POSTGRES_NAME=alquitran_db
      - POSTGRES_USER=alquitran_eduardo
      - POSTGRES_PASSWORD
      - SECRET_KEY

volumes:
  # docker volume create --name=alquitran-data
  alquitrandata:
    external:
      name: alquitran-data
